// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _baseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbaseinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebaseinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbaseinterfacesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebaseinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fullMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createfullinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletefullinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfullinterfacesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemarginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatefullinterfaceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gradientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _creategradientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgradientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updategradientMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _keyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletekeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generatekeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getkeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatehostsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshkeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatekeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}
